# Generated by Django 4.2.7 on 2024-01-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryproject',
            name='city',
        ),
        migrations.RemoveField(
            model_name='countryproject',
            name='user_geo',
        ),
    ]
